# Generated by Django 5.0.4 on 2024-04-05 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Objetos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('precio', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=0)),
                ('fecha_de_registro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDatatables.categoria')),
            ],
            options={
                'verbose_name': 'nombre',
                'verbose_name_plural': 'nombres',
                'ordering': ['id'],
            },
        ),
    ]
