# Generated by Django 5.0.4 on 2024-04-05 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDatatables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['id'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('introduccion', models.TextField(blank=True, null=True)),
                ('foto_1', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('foto_2', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('foto_3', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('foto_4', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('foto_5', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('no_edicion', models.IntegerField(blank=True, default=0, null=True)),
                ('activo', models.BooleanField(default=0)),
                ('fecha_de_registro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDatatables.categoria')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_de_evento', models.DateTimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_1', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('foto_2', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('foto_3', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('foto_4', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('foto_5', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('activo', models.BooleanField(default=0)),
                ('fecha_de_registro', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDatatables.categoria')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Objetos',
        ),
    ]
