# Generated by Django 5.0.4 on 2024-04-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDatatables', '0002_alter_categoria_options_articulo_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='activo',
            field=models.BooleanField(blank=True, default=1, null=True),
        ),
    ]
