# Generated by Django 5.0.4 on 2024-04-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDatatables', '0004_articulo_publicado_evento_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='fecha_de_evento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
