# Generated by Django 5.0.4 on 2024-04-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDatatables', '0005_alter_evento_fecha_de_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='hora_final',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='activo',
            field=models.BooleanField(default=1),
        ),
    ]
