# Generated by Django 5.0.4 on 2024-04-14 05:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDatatables', '0007_alter_articulo_foto_1_alter_articulo_foto_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto_Día',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('activo', models.BooleanField(default=1)),
                ('fecha_de_registro', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': 'Foto del día',
                'verbose_name_plural': 'Foto del día',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('activo', models.BooleanField(default=1)),
                ('fecha_de_registro', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': 'Foto del día',
                'verbose_name_plural': 'Foto del día',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('recomendacion', models.TextField(blank=True, null=True)),
                ('fecha_de_evento', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('foto_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('foto_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('foto_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('foto_4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('foto_5', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('activo', models.BooleanField(default=1)),
                ('fecha_de_registro', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['id'],
            },
        ),
    ]
