# Generated by Django 5.0.4 on 2024-04-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDatatables', '0008_foto_día_logo_partido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('asunto', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, default=1, null=True)),
                ('fecha_de_registro', models.DateTimeField(auto_now_add=True)),
                ('publicado', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'Carta',
                'verbose_name_plural': 'Cartas',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='logo',
            options={'ordering': ['id'], 'verbose_name': 'Logo', 'verbose_name_plural': 'Logo'},
        ),
    ]
