# Generated by Django 5.0.4 on 2024-04-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDatatables', '0009_carta_alter_logo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='descripcion2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='descripcion3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='descripcion4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='descripcion5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='descripcion5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='descripcion2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='descripcion3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='descripcion4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='descripcion5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
