# Generated by Django 5.0.3 on 2024-03-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuario', '0002_usuario_codigo_recuperacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tiempo_expiracion',
            field=models.DateTimeField(null=True, verbose_name='Tiempo de expiración del código de recuperación'),
        ),
    ]
